package profilecapture

import (
	"bytes"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"golang.org/x/net/http/httpguts"

	"github.com/msmythe/mimic/internal/config"
)

var profileNamePattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_-]*$`)

// ProfileOptions controls the generated profile snippet and capture file.
type ProfileOptions struct {
	Name           string
	Output         string
	Force          bool
	Browser        string
	BrowserVersion string
	Platform       string
	Lifecycle      string
	Source         string
	CapturedAt     string
	UserAgent      string
	JA4H           string
	HeaderOrder    []string
	Headers        map[string]string
	MinVersion     string
	MaxVersion     string
}

// WrittenProfile describes the files created for an imported profile.
type WrittenProfile struct {
	ProfilePath string
	CapturePath string
}

// WriteProfile writes a normalized hexadecimal ClientHello and a TOML profile
// snippet beside it. Existing files are preserved unless Force is explicit.
func WriteProfile(result Result, options ProfileOptions) (WrittenProfile, error) {
	if err := ValidateOptions(options); err != nil {
		return WrittenProfile{}, err
	}
	if len(result.ClientHello) == 0 || result.JA4.Fingerprint == "" {
		return WrittenProfile{}, errors.New("cannot write an empty or unanalyzed ClientHello")
	}
	output := options.Output
	if output == "" {
		output = options.Name + ".toml"
	}
	absOutput, err := filepath.Abs(output)
	if err != nil {
		return WrittenProfile{}, fmt.Errorf("resolve output path: %w", err)
	}
	capturePath := strings.TrimSuffix(absOutput, filepath.Ext(absOutput)) + ".clienthello.hex"
	for _, path := range []string{absOutput, capturePath} {
		if !options.Force {
			if _, err := os.Lstat(path); err == nil {
				return WrittenProfile{}, fmt.Errorf("refusing to overwrite %s; use -force to replace it", path)
			} else if !errors.Is(err, os.ErrNotExist) {
				return WrittenProfile{}, fmt.Errorf("inspect output path %s: %w", path, err)
			}
		}
	}
	if err := os.MkdirAll(filepath.Dir(absOutput), 0o755); err != nil {
		return WrittenProfile{}, fmt.Errorf("create output directory: %w", err)
	}

	hexBody := []byte(hex.EncodeToString(result.ClientHello) + "\n")
	if err := writeFile(capturePath, hexBody, options.Force); err != nil {
		return WrittenProfile{}, fmt.Errorf("write ClientHello capture: %w", err)
	}
	profileBody := renderProfile(result, options, filepath.Base(capturePath))
	if err := writeFile(absOutput, profileBody, options.Force); err != nil {
		if !options.Force {
			_ = os.Remove(capturePath)
		}
		return WrittenProfile{}, fmt.Errorf("write profile snippet: %w", err)
	}
	return WrittenProfile{ProfilePath: absOutput, CapturePath: capturePath}, nil
}

func renderProfile(result Result, options ProfileOptions, captureName string) []byte {
	var output bytes.Buffer
	output.WriteString("# Generated by mimic profile. Review HTTP identity before production use.\n")
	if flow := cleanComment(result.Flow); flow != "" {
		fmt.Fprintf(&output, "# Captured flow: %s\n", flow)
	}
	fmt.Fprintf(&output, "[profiles.%s]\n", strconv.Quote(options.Name))
	fmt.Fprintf(&output, "client_hello_file = %s\n", strconv.Quote(filepath.ToSlash(captureName)))
	fmt.Fprintf(&output, "ja4 = %s\n", strconv.Quote(result.JA4.Fingerprint))
	writeTOMLString(&output, "ja4h", options.JA4H)
	writeTOMLString(&output, "browser", options.Browser)
	writeTOMLString(&output, "browser_version", options.BrowserVersion)
	writeTOMLString(&output, "platform", options.Platform)
	writeTOMLString(&output, "lifecycle", options.Lifecycle)
	writeTOMLString(&output, "source", options.Source)
	writeTOMLString(&output, "captured_at", options.CapturedAt)
	writeTOMLString(&output, "user_agent", options.UserAgent)
	writeTOMLArray(&output, "header_order", options.HeaderOrder)
	writeTOMLString(&output, "min_version", options.MinVersion)
	writeTOMLString(&output, "max_version", options.MaxVersion)
	if len(options.Headers) > 0 {
		fmt.Fprintf(&output, "\n[profiles.%s.headers]\n", strconv.Quote(options.Name))
		names := make([]string, 0, len(options.Headers))
		for name := range options.Headers {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			fmt.Fprintf(&output, "%s = %s\n", strconv.Quote(name), strconv.Quote(options.Headers[name]))
		}
	}
	return output.Bytes()
}

func writeTOMLString(output *bytes.Buffer, name, value string) {
	if value != "" {
		fmt.Fprintf(output, "%s = %s\n", name, strconv.Quote(value))
	}
}

func writeTOMLArray(output *bytes.Buffer, name string, values []string) {
	if len(values) == 0 {
		return
	}
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = strconv.Quote(value)
	}
	fmt.Fprintf(output, "%s = [%s]\n", name, strings.Join(quoted, ", "))
}

func writeFile(path string, body []byte, force bool) error {
	if !force {
		file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
		if err != nil {
			return err
		}
		if _, err := file.Write(body); err != nil {
			file.Close()
			_ = os.Remove(path)
			return err
		}
		if err := file.Close(); err != nil {
			_ = os.Remove(path)
			return err
		}
		return nil
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".mimic-profile-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o644); err != nil {
		temporary.Close()
		return err
	}
	if _, err := temporary.Write(body); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}

func cleanComment(value string) string {
	return strings.Join(strings.Fields(value), " ")
}

// ValidateOptions checks generated profile metadata before capture or import.
func ValidateOptions(options ProfileOptions) error {
	if !profileNamePattern.MatchString(options.Name) {
		return errors.New("profile name must contain only letters, numbers, underscores, and hyphens")
	}
	if options.Lifecycle != "" && options.Lifecycle != "current" && options.Lifecycle != "legacy" && options.Lifecycle != "custom" {
		return errors.New("profile lifecycle must be current, legacy, or custom")
	}
	if options.CapturedAt != "" {
		if _, err := time.Parse(time.RFC3339, options.CapturedAt); err != nil {
			return fmt.Errorf("profile captured-at must be RFC3339: %w", err)
		}
	}
	for field, value := range map[string]string{
		"browser": options.Browser, "browser-version": options.BrowserVersion,
		"platform": options.Platform, "source": options.Source,
	} {
		if strings.ContainsAny(value, "\r\n") {
			return fmt.Errorf("profile %s cannot contain newlines", field)
		}
	}
	if options.UserAgent != "" && !httpguts.ValidHeaderFieldValue(options.UserAgent) {
		return errors.New("profile user-agent is not a valid HTTP header value")
	}
	for _, name := range options.HeaderOrder {
		if !httpguts.ValidHeaderFieldName(name) {
			return fmt.Errorf("profile header-order contains invalid HTTP header name %q", name)
		}
	}
	for name, value := range options.Headers {
		if !httpguts.ValidHeaderFieldName(name) {
			return fmt.Errorf("profile headers contain invalid HTTP header name %q", name)
		}
		if !httpguts.ValidHeaderFieldValue(value) {
			return fmt.Errorf("profile header %q is not a valid HTTP header value", name)
		}
	}
	var minVersion, maxVersion uint16
	if options.MinVersion != "" {
		parsed, err := config.TLSVersion(options.MinVersion)
		if err != nil {
			return fmt.Errorf("profile min-version: %w", err)
		}
		minVersion = parsed
	}
	if options.MaxVersion != "" {
		parsed, err := config.TLSVersion(options.MaxVersion)
		if err != nil {
			return fmt.Errorf("profile max-version: %w", err)
		}
		maxVersion = parsed
	}
	if minVersion != 0 && maxVersion != 0 && minVersion > maxVersion {
		return errors.New("profile min-version cannot be higher than max-version")
	}
	return nil
}
